POST http://localhost:8080/pizzas HTTP/1.1
content-type: application/json

{
    "nome": "Pizza de Nutella",
    "preco": 55.9
}

###
GET http://localhost:8080/pizzas HTTP/1.1

###
GET http://localhost:8080/pizzas/4 HTTP/1.1